### ISSUE TITLE
[Suggestion] Columns for Capacities

### ISSUE THREAD

**Issue by maarxx** [koisama/kNumbers#14]
[Suggestion] Columns for Capacities

These are the values like "Consciousness" or "Sight" or "Manipulation" or "Moving".

**Comment by maarxx** [comment]
Pull Request is already open, above.

Meanwhile, implemented here:

https://github.com/maarxx/kNumbers/tree/addCapacities

**Comment by WaKeMaTTa** [comment]
@koisama give us some love :heart: and take care of this repo. =)

**Comment by koisama** [comment]
Merged, added colors.
